# Generated by Django 5.0 on 2023-12-22 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLu',
            fields=[
                ('actionid', models.AutoField(db_column='ActionID', primary_key=True, serialize=False)),
                ('actiondescription', models.CharField(blank=True, db_column='ActionDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'action_lu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagsT',
            fields=[
                ('tagid', models.AutoField(db_column='TagID', primary_key=True, serialize=False)),
                ('tagtype', models.CharField(blank=True, db_column='TagType', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tags_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTagsT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asset_tags_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DassetsT',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('updatedtime', models.DateTimeField(blank=True, db_column='UpdatedTime', null=True)),
            ],
            options={
                'db_table': 'dassets_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmotionLu',
            fields=[
                ('emotionid', models.AutoField(db_column='EmotionID', primary_key=True, serialize=False)),
                ('edescription', models.CharField(blank=True, db_column='EDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'emotion_lu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationLu',
            fields=[
                ('locationid', models.AutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('locationdescription', models.CharField(blank=True, db_column='LocationDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'location_lu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassengertypeLu',
            fields=[
                ('ptypeid', models.AutoField(db_column='PTypeID', primary_key=True, serialize=False)),
                ('pdescription', models.CharField(blank=True, db_column='PDescription', max_length=250, null=True)),
            ],
            options={
                'db_table': 'passengertype_lu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScenarioLu',
            fields=[
                ('scenarioid', models.AutoField(db_column='ScenarioID', primary_key=True, serialize=False)),
                ('sdescription', models.CharField(blank=True, db_column='SDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'scenario_lu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkertypeLu',
            fields=[
                ('wtypeid', models.AutoField(db_column='WTypeID', primary_key=True, serialize=False)),
                ('wdescription', models.CharField(blank=True, db_column='WDescription', max_length=250, null=True)),
            ],
            options={
                'db_table': 'workertype_lu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActiontagT',
            fields=[
                ('tag', models.OneToOneField(db_column='Tag_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='damWebsite.tagst')),
            ],
            options={
                'db_table': 'actiontag_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmotiontagT',
            fields=[
                ('tag', models.OneToOneField(db_column='Tag_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='damWebsite.tagst')),
            ],
            options={
                'db_table': 'emotiontag_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationtagT',
            fields=[
                ('tag', models.OneToOneField(db_column='Tag_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='damWebsite.tagst')),
            ],
            options={
                'db_table': 'locationtag_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScenariotagT',
            fields=[
                ('tag', models.OneToOneField(db_column='Tag_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='damWebsite.tagst')),
            ],
            options={
                'db_table': 'scenariotag_t',
                'managed': False,
            },
        ),
    ]
